# Generated by Django 4.2.7 on 2024-10-10 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
