# Generated by Django 3.2.25 on 2024-06-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240627_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
