# Generated by Django 4.2.7 on 2024-08-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_materials_product_tags_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
