# Generated by Django 4.2.7 on 2024-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fit",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="material_and_care",
            field=models.TextField(blank=True, null=True),
        ),
    ]
