# Generated by Django 4.2.7 on 2024-09-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_fit_product_material_and_care"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="material_and_care",
            new_name="care_instructions",
        ),
    ]
